import { IconGroups } from './types.ts';

export const iconGroups: IconGroups = [
	{
		group: 'Navigation & Arrows',
		icons: [
			'up-caret',
			'down-caret',
			'right-caret',
			'left-caret',
			'up-arrow',
			'down-arrow',
			'right-arrow',
			'left-arrow',
			'bars',
			'forward-slash',
			'close',
		],
	},
	{
		group: 'Actions & Editing',
		icons: [
			'pencil',
			'pen',
			'document',
			'add-document',
			'setting',
			'external',
			'download',
			'cloud-download',
			'rocket',
			'star',
			'puzzle',
			'list-format',
			'random',
			'comment',
			'comment-alt',
			'approve-check',
			'approve-check-circle',
			'translate',
			'heart',
		],
	},
	{
		group: 'Content, Status & System',
		icons: [
			'moon',
			'sun',
			'laptop',
			'open-book',
			'information',
			'magnifier',
			'seti:image',
			'seti:video',
			'seti:audio',
			'seti:todo',
			'seti:plan',
			'seti:pipeline',
			'seti:happenings',
			'seti:lock',
			'seti:license',
			'seti:code-search',
			'email',
			'phone',
			'seti:folder',
			'seti:config',
			'seti:favicon',
			'seti:info',
			'seti:clock',
			'seti:notebook',
			'seti:db',
			'seti:default',
			'seti:shell',
			'seti:ignored',
			'error',
			'warning',
		],
	},
	{
		group: 'Programming & Scripting Languages',
		icons: [
			'seti:c',
			'seti:c-sharp',
			'seti:cpp',
			'seti:coldfusion',
			'seti:d',
			'seti:go',
			'seti:rust',
			'seti:zig',
			'seti:nim',
			'seti:clojure',
			'seti:elixir',
			'seti:elm',
			'seti:f-sharp',
			'seti:haskell',
			'seti:haxe',
			'seti:ocaml',
			'seti:prolog',
			'seti:javascript',
			'seti:typescript',
			'seti:php',
			'seti:python',
			'seti:ruby',
			'seti:dart',
			'seti:livescript',
			'seti:purescript',
			'seti:rescript',
			'seti:lua',
			'seti:perl',
			'seti:R',
			'seti:java',
			'seti:kotlin',
			'seti:scala',
			'seti:swift',
			'seti:vala',
			'seti:crystal',
			'seti:crystal_embedded',
			'seti:hacklang',
			'seti:graphql',
			'seti:argdown',
			'seti:julia',
			'seti:asm',
			'seti:pddl',
			'seti:powershell',
		],
	},
	{
		group: 'Web & Markup',
		icons: [
			'seti:html',
			'seti:jade',
			'seti:pug',
			'seti:liquid',
			'seti:twig',
			'seti:nunjucks',
			'seti:haml',
			'seti:jinja',
			'seti:mustache',

			'seti:css',
			'seti:sass',
			'seti:stylus',
			'seti:slim',
			'seti:smarty',

			'seti:xml',
			'seti:json',
			'seti:yml',
			'seti:markdown',
			'mdx',
		],
	},
	{
		group: 'Frameworks & Tools',
		icons: [
			'seti:react',
			'seti:vue',
			'seti:svelte',
			'astro',
			'alpine',
			'node',
			'deno',
			'bun',
			'seti:platformio',
			'biome',
			'pkl',
			'seti:cu',
			'seti:cake',
			'seti:cake_php',
			'seti:odata',
			'backstage',
			'starlight',
			'seti:grails',
			'seti:spring',
			'seti:ionic',
		],
	},
	{
		group: 'Package Managers & Build Systems',
		icons: [
			'seti:maven',
			'seti:gradle',
			'seti:bazel',
			'seti:sbt',
			'pnpm',
			'seti:yarn',
			'seti:npm',
			'npm',
			'seti:webpack',
			'seti:rollup',
			'seti:vite',
			'jsr',
			'seti:hex',
			'homebrew',
			'nix',
			'seti:babel',
			'seti:bower',
			'seti:makefile',
			'seti:gulp',
			'seti:grunt',
			'seti:elixir_script',
		],
	},
	{
		group: 'Development Services',
		icons: [
			'seti:github',
			'seti:gitlab',
			'azureDevOps',
			'vercel',
			'netlify',
			'cloudflare',
			'github',
			'gitlab',
			'codePen',
			'codeberg',
			'stackOverflow',
			'sourcehut',
			'bitbucket',
			'hackerOne',
			'seti:bsl',
			'seti:mdo',
			'seti:code-climate',
			'seti:firebase',
			'seti:heroku',
			'seti:ethereum',
			'seti:salesforce',
			'seti:bicep',
			'seti:prisma',
		],
	},
	{
		group: 'Development Tools',
		icons: [
			'seti:docker',
			'seti:jenkins',
			'seti:git',
			'storybook',
			'confluence',
			'jira',
			'vscode',
			'jetbrains',
			'zed',
			'vim',
			'seti:sublime',
			'seti:eslint',
			'seti:stylelint',
			'seti:terraform',
			'seti:puppet',
			'seti:karma',
		],
	},
	{
		group: 'Word Processing, Design & Media',
		icons: [
			'seti:illustrator',
			'seti:photoshop',
			'figma',
			'sketch',
			'seti:godot',
			'seti:word',
			'seti:firefox',
		],
	},
	{
		group: 'File types, Files & Protocols',
		icons: [
			'seti:svg',
			'seti:font',
			'seti:pdf',
			'rss',
			'seti:csv',
			'seti:xls',
			'seti:tex',
			'seti:zip',
			'seti:wgt',
			'seti:wasm',
			'seti:wat',
			'seti:tsconfig',
		],
	},

	{
		group: 'Content Creators',
		icons: [
			'twitch',
			'instagram',
			'reddit',
			'patreon',
			'youtube',
			'pinterest',
			'tiktok',
			'substack',
			'openCollective',
		],
	},

	{
		group: 'Social Networks',
		icons: [
			'linkedin',
			'twitter',
			'x.com',
			'mastodon',
			'facebook',
			'threads',
			'blueSky',
			'farcaster',
			'nostr',
		],
	},
	{
		group: 'Communication',
		icons: [
			'discord',
			'discourse',
			'gitter',
			'telegram',
			'signal',
			'slack',
			'matrix',
			'microsoftTeams',
			'zulip',
		],
	},
	{
		group: 'OS & Platforms',
		icons: ['seti:windows', 'linux', 'apple'],
	},
];
