import { IconInfo } from './types.ts';

export const iconInfo: IconInfo = {
	// from file-tree-icons.ts
	'seti:folder': {
		url: '',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/folder.svg',
		desc: 'Folder icon from Seti UI',
	},
	'seti:bsl': {
		url: 'https://1c-dn.com/1c_enterprise/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/bsl.svg',
		desc: 'Business Scripting Language (BSL) source file for 1C:Enterprise, a business automation platform',
	},
	'seti:mdo': {
		url: 'https://1c-dn.com/1c_enterprise/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/mdo.svg',
		desc: 'Metadata Object (MDO) file used in 1C:Enterprise configurations',
	},
	'seti:salesforce': {
		url: 'https://www.salesforce.com/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/salesforce.svg',
		desc: 'Single CRM tool for Sales, Customer Service, Marketing, Commerce & IT.',
	},
	'seti:asm': {
		url: 'https://en.wikipedia.org/wiki/Assembly_language',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/asm.svg',
		desc: 'Assembly language programming icon',
	},
	'seti:bicep': {
		url: 'https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/overview?tabs=bicep',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/bicep.svg',
		desc: 'Bicep is a domain-specific language that uses declarative syntax to deploy Azure resources.',
	},
	'seti:bazel': {
		url: 'https://bazel.build/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/bazel.svg',
		desc: 'Build and test software of any size, quickly and reliably.',
	},
	'seti:c': {
		url: 'https://www.c-language.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/c.svg',
		desc: 'C programming language',
	},
	'seti:c-sharp': {
		url: 'https://learn.microsoft.com/en-us/dotnet/csharp/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/c-sharp.svg',
		desc: 'Modern, open-source, object-oriented programming language developed by Microsoft',
	},
	'seti:html': {
		url: 'https://html.spec.whatwg.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/html.svg',
		desc: 'Hypertext Markup Language (HTML) is the standard markup language for documents designed to be displayed in a web browser.',
	},
	'seti:cpp': {
		url: 'https://isocpp.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/cpp.svg',
		desc: 'C++ is a high-level, general-purpose programming language created by Danish computer scientist Bjarne Stroustrup.',
	},
	'seti:clojure': {
		url: 'https://clojure.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/clojure.svg',
		desc: 'Clojure is a robust, practical, and fast programming language with a set of useful features that together form a simple, coherent, and powerful tool.',
	},
	'seti:coldfusion': {
		url: 'https://www.adobe.com/products/coldfusion-family.html',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/coldfusion.svg',
		desc: 'An Adobe web application development platform and its associated ColdFusion Markup Language (CFML), which simplifies connecting to databases and creating dynamic web pages',
	},
	'seti:config': {
		url: '',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/config.svg',
		desc: 'Gear icon representing configuration or settings',
	},
	'seti:crystal': {
		url: 'https://crystal-lang.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/crystal.svg',
		desc: 'A high-level general-purpose, object-oriented programming language.',
	},
	'seti:crystal_embedded': {
		url: 'https://crystal-lang.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/crystal_embedded.svg',
		desc: 'A high-level general-purpose, object-oriented programming language.',
	},
	'seti:json': {
		url: 'https://www.json.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/json.svg',
		desc: 'JSON file format',
	},
	'seti:css': {
		url: 'https://www.w3.org/Style/CSS/Overview.en.html',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/css.svg',
		desc: 'Cascading Style Sheets file',
	},
	'seti:csv': {
		url: 'https://tools.ietf.org/html/rfc4180',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/csv.svg',
		desc: 'Comma-separated values file',
	},
	'seti:xls': {
		url: 'https://www.microsoft.com/en-us/microsoft-365/excel',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/xls.svg',
		desc: 'Microsoft Excel spreadsheet',
	},
	'seti:cu': {
		url: 'https://developer.nvidia.com/cuda-zone',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/cu.svg',
		desc: 'Parallel computing platform and API model from NVIDIA',
	},
	'seti:cake': {
		url: 'https://cakephp.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/cake.svg',
		desc: 'Open-source web framework for PHP',
	},
	'seti:cake_php': {
		url: 'https://cakephp.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/cake_php.svg',
		desc: 'Open-source web framework for PHP',
	},
	'seti:d': {
		url: 'https://dlang.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/d.svg',
		desc: 'D is a systems programming language with C-like syntax and performance',
	},
	'seti:word': {
		url: 'https://www.microsoft.com/en-us/microsoft-365/word',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/word.svg',
		desc: 'Microsoft Word – word processing software',
	},
	'seti:elixir': {
		url: 'https://elixir-lang.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/elixir.svg',
		desc: 'Elixir is a dynamic, functional language for building scalable and maintainable applications',
	},
	'seti:elixir_script': {
		url: 'https://elixirscript.github.io/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/elixir_script.svg',
		desc: 'ElixirScript compiles Elixir code to JavaScript',
	},
	'seti:hex': {
		url: 'https://hex.pm/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/hex.svg',
		desc: 'Hex is the package manager for the Erlang ecosystem',
	},
	'seti:elm': {
		url: 'https://elm-lang.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/elm.svg',
		desc: 'Elm is a functional language for building web browser-based graphical user interfaces',
	},
	'seti:favicon': {
		url: '',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/favicon.svg',
		desc: 'Favicon file icon',
	},
	'seti:f-sharp': {
		url: 'https://learn.microsoft.com/en-us/dotnet/fsharp/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/f-sharp.svg',
		desc: 'F# is a functional-first programming language on the .NET platform',
	},
	'seti:git': {
		url: 'https://git-scm.com/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/git.svg',
		desc: 'Distributed version control system',
	},
	'seti:go': {
		url: 'https://golang.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/go.svg',
		desc: 'Open-source programming language developed by Google',
	},
	'seti:godot': {
		url: 'https://godotengine.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/godot.svg',
		desc: 'Open-source game engine for 2D and 3D games',
	},
	'seti:gradle': {
		url: 'https://gradle.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/gradle.svg',
		desc: 'Open-source build automation tool',
	},
	'seti:grails': {
		url: 'https://grails.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/grails.svg',
		desc: 'Web application framework that uses Groovy',
	},
	'seti:graphql': {
		url: 'https://graphql.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/graphql.svg',
		desc: 'Query language for APIs and a runtime for executing those queries',
	},
	'seti:hacklang': {
		url: 'https://hacklang.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/hacklang.svg',
		desc: 'Programming language developed by Facebook, based on PHP',
	},
	'seti:haml': {
		url: 'http://haml.info/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/haml.svg',
		desc: 'HTML abstraction markup language',
	},
	'seti:mustache': {
		url: 'https://mustache.github.io/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/mustache.svg',
		desc: 'Logic-less template syntax for web and app development',
	},
	'seti:haskell': {
		url: 'https://www.haskell.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/haskell.svg',
		desc: 'Standardized, general-purpose purely functional programming language',
	},
	'seti:haxe': {
		url: 'https://haxe.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/haxe.svg',
		desc: 'High-level, cross-platform programming language and compiler',
	},
	'seti:jade': {
		url: 'https://pugjs.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/jade.svg',
		desc: 'Template engine for Node.js, now known as Pug',
	},
	'seti:java': {
		url: 'https://www.java.com/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/java.svg',
		desc: 'High-level, class-based, object-oriented programming language',
	},
	'seti:javascript': {
		url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/javascript.svg',
		desc: 'High-level, interpreted programming language used primarily for web development',
	},
	'seti:jinja': {
		url: 'https://palletsprojects.com/p/jinja/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/jinja.svg',
		desc: 'Templating engine for Python',
	},
	'seti:julia': {
		url: 'https://julialang.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/julia.svg',
		desc: 'High-level, high-performance dynamic programming language for technical computing',
	},
	'seti:karma': {
		url: 'https://karma-runner.github.io/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/karma.svg',
		desc: 'Test runner for JavaScript',
	},
	'seti:kotlin': {
		url: 'https://kotlinlang.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/kotlin.svg',
		desc: 'Modern, statically typed programming language for JVM and Android',
	},
	'seti:dart': {
		url: 'https://dart.dev/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/dart.svg',
		desc: 'Client-optimized programming language for fast apps on any platform',
	},
	'seti:liquid': {
		url: 'https://shopify.github.io/liquid/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/liquid.svg',
		desc: 'Template language for web development, used by Shopify',
	},
	'seti:livescript': {
		url: 'https://livescript.net/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/livescript.svg',
		desc: 'Functional programming language that compiles to JavaScript',
	},
	'seti:lua': {
		url: 'https://www.lua.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/lua.svg',
		desc: 'Lightweight, high-level, multi-paradigm programming language',
	},
	'seti:markdown': {
		url: 'https://daringfireball.net/projects/markdown/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/markdown.svg',
		desc: 'Lightweight markup language for formatting text',
	},
	'seti:argdown': {
		url: 'https://argdown.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/argdown.svg',
		desc: 'Markup language for argumentation',
	},
	'seti:info': {
		url: '',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/info.svg',
		desc: 'Information icon',
	},
	'seti:clock': {
		url: '',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/clock.svg',
		desc: 'Clock or time icon',
	},
	'seti:maven': {
		url: 'https://maven.apache.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/maven.svg',
		desc: 'Build automation tool used primarily for Java projects',
	},
	'seti:nim': {
		url: 'https://nim-lang.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/nim.svg',
		desc: 'Statically typed compiled systems programming language',
	},
	'seti:github': {
		url: 'https://github.com/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/github.svg',
		desc: 'Platform for hosting and collaborating on Git repositories',
	},
	'seti:notebook': {
		url: '',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/notebook.svg',
		desc: 'Notebook icon',
	},
	'seti:nunjucks': {
		url: 'https://mozilla.github.io/nunjucks/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/nunjucks.svg',
		desc: 'Templating engine for JavaScript',
	},
	'seti:npm': {
		url: 'https://www.npmjs.com/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/npm.svg',
		desc: 'Package manager for JavaScript',
	},
	'seti:ocaml': {
		url: 'https://ocaml.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/ocaml.svg',
		desc: 'General-purpose programming language with an emphasis on expressiveness and safety',
	},
	'seti:odata': {
		url: 'https://www.odata.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/odata.svg',
		desc: 'Open protocol for building and consuming RESTful APIs',
	},
	'seti:perl': {
		url: 'https://www.perl.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/perl.svg',
		desc: 'High-level, general-purpose, interpreted programming language',
	},
	'seti:php': {
		url: 'https://www.php.net/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/php.svg',
		desc: 'Popular general-purpose scripting language especially suited to web development',
	},
	'seti:pipeline': {
		url: '',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/pipeline.svg',
		desc: 'Pipeline icon representing CI/CD or data pipelines',
	},
	'seti:pddl': {
		url: 'https://en.wikipedia.org/wiki/Planning_Domain_Definition_Language',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/pddl.svg',
		desc: 'Language used in artificial intelligence for automated planning',
	},
	'seti:plan': {
		url: '',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/plan.svg',
		desc: 'Plan or project icon',
	},
	'seti:happenings': {
		url: '',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/happenings.svg',
		desc: 'Happenings or events icon',
	},
	'seti:powershell': {
		url: 'https://learn.microsoft.com/powershell/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/powershell.svg',
		desc: 'Task automation and configuration management framework from Microsoft',
	},
	'seti:prisma': {
		url: 'https://www.prisma.io/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/prisma.svg',
		desc: 'Next-generation ORM for Node.js & TypeScript',
	},
	'seti:pug': {
		url: 'https://pugjs.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/pug.svg',
		desc: 'High-performance template engine for Node.js',
	},
	'seti:puppet': {
		url: 'https://puppet.com/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/puppet.svg',
		desc: 'Automation software for configuration management',
	},
	'seti:purescript': {
		url: 'https://www.purescript.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/purescript.svg',
		desc: 'Strongly-typed functional programming language that compiles to JavaScript',
	},
	'seti:python': {
		url: 'https://www.python.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/python.svg',
		desc: 'High-level, interpreted, general-purpose programming language',
	},
	'seti:react': {
		url: 'https://reactjs.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/react.svg',
		desc: 'JavaScript library for building user interfaces',
	},
	'seti:rescript': {
		url: 'https://rescript-lang.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/rescript.svg',
		desc: 'Strongly-typed language that compiles to JavaScript',
	},
	'seti:R': {
		url: 'https://www.r-project.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/R.svg',
		desc: 'Programming language and environment for statistical computing and graphics',
	},
	'seti:ruby': {
		url: 'https://www.ruby-lang.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/ruby.svg',
		desc: 'Dynamic, open source programming language with a focus on simplicity and productivity',
	},
	'seti:rust': {
		url: 'https://www.rust-lang.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/rust.svg',
		desc: 'Systems programming language focused on safety, speed, and concurrency',
	},
	'seti:sass': {
		url: 'https://sass-lang.com/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/sass.svg',
		desc: 'CSS preprocessor with variables, nested rules, and more',
	},
	'seti:spring': {
		url: 'https://spring.io/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/spring.svg',
		desc: 'Application framework and inversion of control container for Java',
	},
	'seti:slim': {
		url: 'http://slim-lang.com/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/slim.svg',
		desc: 'Lightweight templating engine for Ruby',
	},
	'seti:smarty': {
		url: 'https://www.smarty.net/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/smarty.svg',
		desc: 'Template engine for PHP',
	},
	'seti:sbt': {
		url: 'https://www.scala-sbt.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/sbt.svg',
		desc: 'Build tool for Scala and Java projects',
	},
	'seti:scala': {
		url: 'https://www.scala-lang.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/scala.svg',
		desc: 'High-level programming language combining object-oriented and functional programming',
	},
	'seti:ethereum': {
		url: 'https://ethereum.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/ethereum.svg',
		desc: 'Decentralized, open-source blockchain featuring smart contract functionality',
	},
	'seti:stylus': {
		url: 'https://stylus-lang.com/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/stylus.svg',
		desc: 'Expressive, dynamic CSS preprocessor',
	},
	'seti:svelte': {
		url: 'https://svelte.dev/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/svelte.svg',
		desc: 'Frontend framework that compiles components to highly efficient JavaScript',
	},
	'seti:swift': {
		url: 'https://swift.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/swift.svg',
		desc: 'Powerful and intuitive programming language for iOS, macOS, watchOS, and tvOS',
	},
	'seti:db': {
		url: '',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/db.svg',
		desc: 'Database icon',
	},
	'seti:terraform': {
		url: 'https://www.terraform.io/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/terraform.svg',
		desc: 'Infrastructure as code software tool for building, changing, and versioning infrastructure',
	},
	'seti:tex': {
		url: 'https://www.latex-project.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/tex.svg',
		desc: 'Typesetting system commonly used for technical and scientific documents',
	},
	'seti:default': {
		url: '',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/default.svg',
		desc: 'Generic default icon used when no specific match is found',
	},
	'seti:twig': {
		url: 'https://twig.symfony.com/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/twig.svg',
		desc: 'Flexible, fast, and secure template engine for PHP',
	},
	'seti:typescript': {
		url: 'https://www.typescriptlang.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/typescript.svg',
		desc: 'Typed superset of JavaScript that compiles to plain JavaScript',
	},
	'seti:tsconfig': {
		url: 'https://www.typescriptlang.org/tsconfig',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/tsconfig.svg',
		desc: 'Configuration file for TypeScript projects',
	},
	'seti:vala': {
		url: 'https://vala.dev/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/vala.svg',
		desc: 'Programming language that brings modern language features to GNOME developers',
	},
	'seti:vite': {
		url: 'https://vitejs.dev/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/vite.svg',
		desc: 'Next generation front-end tooling for fast development',
	},
	'seti:vue': {
		url: 'https://vuejs.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/vue.svg',
		desc: 'Progressive JavaScript framework for building user interfaces',
	},
	'seti:wasm': {
		url: 'https://webassembly.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/wasm.svg',
		desc: 'Binary instruction format for a stack-based virtual machine, enabling high-performance apps on the web',
	},
	'seti:wat': {
		url: 'https://webassembly.github.io/spec/core/text/index.html',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/wat.svg',
		desc: 'WebAssembly Text format, human-readable representation of WASM bytecode',
	},
	'seti:xml': {
		url: 'https://www.w3.org/XML/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/xml.svg',
		desc: 'Markup language defining a set of rules for encoding documents in a format readable by both humans and machines',
	},
	'seti:yml': {
		url: 'https://yaml.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/yml.svg',
		desc: 'Human-readable data serialization standard',
	},
	'seti:prolog': {
		url: 'https://www.swi-prolog.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/prolog.svg',
		desc: 'Logic programming language used in AI and computational linguistics',
	},
	'seti:zig': {
		url: 'https://ziglang.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/zig.svg',
		desc: 'General-purpose programming language designed for robustness, optimality, and maintainability',
	},
	'seti:zip': {
		url: 'https://www.pkware.com/software/zip',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/zip.svg',
		desc: 'Archive file format that supports lossless data compression',
	},
	'seti:wgt': {
		url: 'https://www.w3.org/TR/widgets/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/wgt.svg',
		desc: 'Widget archive file format, used for packaging web or mobile widgets',
	},
	'seti:illustrator': {
		url: 'https://www.adobe.com/products/illustrator.html',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/illustrator.svg',
		desc: 'Adobe Illustrator – vector graphics editor',
	},
	'seti:photoshop': {
		url: 'https://www.adobe.com/products/photoshop.html',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/photoshop.svg',
		desc: 'Adobe Photoshop – raster graphics editor',
	},
	'seti:pdf': {
		url: 'https://www.adobe.com/acrobat/pdf-reader.html',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/pdf.svg',
		desc: 'Portable Document Format (PDF) for documents and forms',
	},
	'seti:font': {
		url: 'https://fonts.google.com/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/font.svg',
		desc: 'Font file or typeface',
	},
	'seti:image': {
		url: '',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/image.svg',
		desc: 'Generic image file',
	},
	'seti:svg': {
		url: 'https://www.w3.org/Graphics/SVG/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/svg.svg',
		desc: 'Scalable Vector Graphics format',
	},
	'seti:sublime': {
		url: 'https://www.sublimetext.com/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/sublime.svg',
		desc: 'Sublime Text – sophisticated text editor for code, markup, and prose',
	},
	'seti:code-search': {
		url: '',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/code-search.svg',
		desc: 'Generic code search icon',
	},
	'seti:shell': {
		url: '',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/shell.svg',
		desc: 'Command-line shell or script',
	},
	'seti:video': {
		url: '',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/video.svg',
		desc: 'Generic video file',
	},
	'seti:audio': {
		url: '',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/audio.svg',
		desc: 'Generic audio file',
	},
	'seti:windows': {
		url: 'https://www.microsoft.com/windows',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/windows.svg',
		desc: 'Microsoft Windows operating system',
	},
	'seti:jenkins': {
		url: 'https://www.jenkins.io/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/jenkins.svg',
		desc: 'Automation server for building, deploying, and automating projects',
	},
	'seti:babel': {
		url: 'https://babeljs.io/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/babel.svg',
		desc: 'JavaScript compiler that lets you use next generation JavaScript, today',
	},
	'seti:bower': {
		url: 'https://bower.io/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/bower.svg',
		desc: 'Package manager for the web',
	},
	'seti:docker': {
		url: 'https://www.docker.com/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/docker.svg',
		desc: 'Platform for developing, shipping, and running applications in containers',
	},
	'seti:code-climate': {
		url: 'https://codeclimate.com/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/code-climate.svg',
		desc: 'Automated code review and quality analysis platform',
	},
	'seti:eslint': {
		url: 'https://eslint.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/eslint.svg',
		desc: 'Pluggable JavaScript and JSX linter',
	},
	'seti:firebase': {
		url: 'https://firebase.google.com/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/firebase.svg',
		desc: "Google's platform for building mobile and web applications",
	},
	'seti:firefox': {
		url: 'https://www.mozilla.org/firefox/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/firefox.svg',
		desc: 'Mozilla Firefox web browser',
	},
	'seti:gitlab': {
		url: 'https://gitlab.com/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/gitlab.svg',
		desc: 'Git repository manager providing CI/CD pipelines',
	},
	'seti:grunt': {
		url: 'https://gruntjs.com/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/grunt.svg',
		desc: 'JavaScript task runner',
	},
	'seti:gulp': {
		url: 'https://gulpjs.com/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/gulp.svg',
		desc: 'Streaming build system for automating tasks in development',
	},
	'seti:ionic': {
		url: 'https://ionicframework.com/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/ionic.svg',
		desc: 'Cross-platform mobile app development framework',
	},
	'seti:platformio': {
		url: 'https://platformio.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/platformio.svg',
		desc: 'Open source ecosystem for IoT development',
	},
	'seti:rollup': {
		url: 'https://rollupjs.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/rollup.svg',
		desc: 'JavaScript module bundler',
	},
	'seti:stylelint': {
		url: 'https://stylelint.io/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/stylelint.svg',
		desc: 'Modern CSS linter',
	},
	'seti:yarn': {
		url: 'https://yarnpkg.com/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/yarn.svg',
		desc: 'Fast, reliable, and secure dependency management',
	},
	'seti:webpack': {
		url: 'https://webpack.js.org/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/webpack.svg',
		desc: 'Static module bundler for JavaScript applications',
	},
	'seti:lock': {
		url: '',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/lock.svg',
		desc: 'Represents a lock file or security setting',
	},
	'seti:license': {
		url: '',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/license.svg',
		desc: 'Represents licensing information or files',
	},
	'seti:makefile': {
		url: 'https://www.gnu.org/software/make/manual/make.html',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/makefile.svg',
		desc: 'Make is a build automation tool that automatically builds executable programs and libraries from source code',
	},
	'seti:heroku': {
		url: 'https://www.heroku.com/',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/heroku.svg',
		desc: 'Cloud platform as a service for deploying apps',
	},
	'seti:todo': {
		url: '',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/todo.svg',
		desc: 'Represents a to-do item',
	},
	'seti:ignored': {
		url: '',
		source: 'https://github.com/jesseweed/seti-ui/blob/master/icons/ignored.svg',
		desc: 'Represents ignored files or items',
	},

	// from Icons.ts
	'up-caret': { url: '', source: '', desc: 'Upward pointing caret icon' },
	'down-caret': { url: '', source: '', desc: 'Downward pointing caret icon' },
	'right-caret': { url: '', source: '', desc: 'Right pointing caret icon' },
	'left-caret': { url: '', source: '', desc: 'Left pointing caret icon' },
	'up-arrow': { url: '', source: '', desc: 'Upward pointing arrow' },
	'down-arrow': { url: '', source: '', desc: 'Downward pointing arrow' },
	'right-arrow': { url: '', source: '', desc: 'Right pointing arrow' },
	'left-arrow': { url: '', source: '', desc: 'Left pointing arrow' },
	bars: { url: '', source: '', desc: 'Menu bars / hamburger icon' },
	translate: { url: '', source: '', desc: 'Translation / language icon' },
	pencil: { url: '', source: '', desc: 'Pencil / edit icon' },
	pen: { url: '', source: '', desc: 'Pen / write icon' },
	document: { url: '', source: '', desc: 'Generic document/file icon' },
	'add-document': { url: '', source: '', desc: 'Icon representing adding a new document' },
	setting: { url: '', source: '', desc: 'Settings / gear icon' },
	external: { url: '', source: '', desc: 'External link / open in new tab icon' },
	download: { url: '', source: '', desc: 'Download icon' },
	'cloud-download': { url: '', source: '', desc: 'Download from cloud icon' },
	moon: { url: '', source: '', desc: 'Moon / dark mode icon' },
	sun: { url: '', source: '', desc: 'Sun / light mode icon' },
	laptop: { url: '', source: '', desc: 'Laptop / device icon' },
	'open-book': { url: '', source: '', desc: 'Open book / reading icon' },
	information: { url: '', source: '', desc: 'Information / info icon' },
	magnifier: { url: '', source: '', desc: 'Magnifying glass / search icon' },
	'forward-slash': { url: '', source: '', desc: 'Forward slash symbol icon' },
	close: { url: '', source: '', desc: 'Close / X icon' },
	error: { url: '', source: '', desc: 'Error / alert icon' },
	warning: { url: '', source: '', desc: 'Warning / caution icon' },
	'approve-check-circle': {
		url: '',
		source: '',
		desc: 'Checkmark inside a circle / approved icon',
	},
	'approve-check': { url: '', source: '', desc: 'Checkmark / approval icon' },
	rocket: { url: '', source: '', desc: 'Rocket / launch icon' },
	star: { url: '', source: '', desc: 'Star / favorite icon' },
	puzzle: { url: '', source: '', desc: 'Puzzle piece / integration or extension icon' },
	'list-format': { url: '', source: '', desc: 'List / bullet points icon' },
	random: { url: '', source: '', desc: 'Random / shuffle icon' },
	comment: { url: '', source: '', desc: 'Comment / chat icon' },
	'comment-alt': { url: '', source: '', desc: 'Alternate style comment / chat icon' },
	heart: { url: '', source: '', desc: 'Heart / like / favorite icon' },
	github: { url: 'https://github.com/', source: '', desc: 'GitHub code hosting platform' },
	gitlab: { url: 'https://gitlab.com/', source: '', desc: 'GitLab code hosting platform' },
	bitbucket: {
		url: 'https://bitbucket.org/',
		source: '',
		desc: 'Bitbucket Git repository hosting service',
	},
	codePen: {
		url: 'https://codepen.io/',
		source: '',
		desc: 'Online code editor for HTML, CSS, JS',
	},
	farcaster: {
		url: 'https://www.farcaster.xyz/',
		source: '',
		desc: 'Decentralized social network',
	},
	discord: { url: 'https://discord.com/', source: '', desc: 'Chat and community platform' },
	gitter: {
		url: 'https://gitter.im/',
		source: '',
		desc: 'Chat and collaboration for developers',
	},
	twitter: {
		url: 'https://twitter.com/',
		source: '',
		desc: 'Social networking platform (now X)',
	},
	'x.com': {
		url: 'https://x.com/',
		source: '',
		desc: 'Official website for X, formerly Twitter',
	},
	mastodon: {
		url: 'https://joinmastodon.org/',
		source: '',
		desc: 'Decentralized social network',
	},
	codeberg: {
		url: 'https://codeberg.org/',
		source: '',
		desc: 'Git hosting service powered by Gitea',
	},
	youtube: { url: 'https://www.youtube.com/', source: '', desc: 'Video sharing platform' },
	threads: {
		url: 'https://www.threads.com/',
		source: '',
		desc: 'Text-based social network by Meta',
	},
	linkedin: {
		url: 'https://www.linkedin.com/',
		source: '',
		desc: 'Professional networking platform',
	},
	twitch: {
		url: 'https://www.twitch.tv/',
		source: '',
		desc: 'Live streaming platform for gamers',
	},
	azureDevOps: {
		url: 'https://azure.microsoft.com/en-us/services/devops/',
		source: '',
		desc: 'Microsoft Azure DevOps: DevOps services for CI/CD and project management',
	},
	microsoftTeams: {
		url: 'https://www.microsoft.com/en-us/microsoft-teams/group-chat-software',
		source: '',
		desc: 'Collaboration and chat platform by Microsoft',
	},
	instagram: {
		url: 'https://www.instagram.com/',
		source: '',
		desc: 'Photo and video sharing social network',
	},
	stackOverflow: {
		url: 'https://stackoverflow.com/',
		source: '',
		desc: 'Q&A platform for programmers',
	},
	telegram: { url: 'https://telegram.org/', source: '', desc: 'Cloud-based messaging app' },
	rss: {
		url: '',
		source: 'https://www.rssboard.org/',
		desc: 'Really Simple Syndication (RSS) is a Web content syndication format',
	},
	facebook: { url: 'https://www.facebook.com/', source: '', desc: 'Social networking platform' },
	email: { url: '', source: '', desc: 'Generic email icon' },
	phone: { url: '', source: '', desc: 'Generic phone icon' },
	reddit: {
		url: 'https://www.reddit.com/',
		source: '',
		desc: 'Social news aggregation and discussion platform',
	},
	patreon: {
		url: 'https://www.patreon.com/',
		source: '',
		desc: 'Membership platform for creators',
	},
	signal: { url: 'https://signal.org/', source: '', desc: 'Secure messaging app' },
	slack: { url: 'https://slack.com/', source: '', desc: 'Collaboration and messaging platform' },
	matrix: {
		url: 'https://matrix.org/',
		source: '',
		desc: 'Open standard for decentralized communication',
	},
	hackerOne: {
		url: 'https://www.hackerone.com/',
		source: '',
		desc: 'Platform for coordinated vulnerability disclosure and bug bounties',
	},
	openCollective: {
		url: 'https://opencollective.com/',
		source: '',
		desc: 'Platform for funding open-source projects and communities',
	},
	blueSky: { url: 'https://blueskyweb.xyz/', source: '', desc: 'Decentralized social network' },
	discourse: {
		url: 'https://www.discourse.org/',
		source: '',
		desc: 'Modern discussion forum platform',
	},
	zulip: {
		url: 'https://zulip.com/',
		source: '',
		desc: 'Team chat platform with topic threading',
	},
	pinterest: {
		url: 'https://www.pinterest.com/',
		source: '',
		desc: 'Image sharing and social media platform',
	},
	tiktok: {
		url: 'https://www.tiktok.com/',
		source: '',
		desc: 'Short-form video sharing platform',
	},
	astro: {
		url: 'https://astro.build/',
		source: 'https://iconify.design/docs/usage/svg/astro/',
		desc: 'Modern static site generator',
	},
	alpine: {
		url: 'https://alpinejs.dev/',
		source: '',
		desc: 'Lightweight JavaScript framework for declarative UI',
	},
	pnpm: {
		url: 'https://pnpm.io/',
		source: '',
		desc: 'Fast, disk space-efficient package manager for Node.js',
	},
	biome: {
		url: 'https://biomejs.dev/',
		source: '',
		desc: 'All-in-one code linter, formatter, and bundler',
	},
	bun: {
		url: 'https://bun.sh/',
		source: '',
		desc: 'Fast JavaScript runtime, bundler, and package manager',
	},
	mdx: {
		url: 'https://mdxjs.com/',
		source: '',
		desc: 'JSX in Markdown for component-driven content',
	},
	apple: {
		url: 'https://www.apple.com/',
		source: '',
		desc: 'Technology company and product ecosystem',
	},
	linux: {
		url: 'https://en.wikipedia.org/wiki/Linux',
		source: '',
		desc: 'Open-source operating system kernel',
	},
	homebrew: { url: 'https://brew.sh/', source: '', desc: 'Package manager for macOS and Linux' },
	nix: {
		url: 'https://nixos.org/nix/',
		source: '',
		desc: 'Functional package manager for Linux and macOS',
	},
	starlight: {
		url: 'https://astro.build/starlight',
		source: '',
		desc: 'Documentation framework for Astro',
	},
	pkl: {
		url: 'https://pkl-lang.org/',
		source: '',
		desc: 'Configuration-as-code language with rich validation and tooling.',
	},
	node: {
		url: 'https://nodejs.org/',
		source: '',
		desc: "JavaScript runtime built on Chrome's V8 engine",
	},
	cloudflare: {
		url: 'https://www.cloudflare.com/',
		source: '',
		desc: 'Web performance and security company',
	},
	vercel: {
		url: 'https://vercel.com/',
		source: '',
		desc: 'Platform for frontend frameworks and static sites',
	},
	netlify: {
		url: 'https://www.netlify.com/',
		source: '',
		desc: 'Cloud platform for deploying static websites and serverless functions',
	},
	deno: {
		url: 'https://deno.land/',
		source: '',
		desc: 'Secure JavaScript and TypeScript runtime',
	},
	jsr: {
		url: 'https://jsr.io/',
		source: '',
		desc: 'Open-source package registry for modern JavaScript and TypeScript',
	},
	nostr: { url: 'https://nostr.com/', source: '', desc: 'Decentralized social network protocol' },
	backstage: {
		url: 'https://backstage.io/',
		source: '',
		desc: 'Open platform for building developer portals',
	},
	confluence: {
		url: 'https://duckduckgo.com/?q=https%3A%2F%2Fwww.atlassian.com%2Fsoftware%2Fconfluence', // https://www.atlassian.com/software/confluence // blocked github referrer
		source: '',
		desc: 'Collaboration and documentation software from Atlassian',
	},
	jira: {
		url: 'https://duckduckgo.com/?q=https%3A%2F%2Fwww.atlassian.com%2Fsoftware%2Fjira', // https://www.atlassian.com/software/jira // blocked github referrer
		source: '',
		desc: 'Project management and issue tracking software from Atlassian',
	},
	storybook: {
		url: 'https://storybook.js.org/',
		source: '',
		desc: 'UI component development environment',
	},
	vscode: {
		url: 'https://code.visualstudio.com/',
		source: '',
		desc: 'Source-code editor developed by Microsoft',
	},
	jetbrains: { url: 'https://www.jetbrains.com/', source: '', desc: 'Developer tools and IDEs' },
	zed: { url: 'https://zed.dev/', source: '', desc: 'Modern text editor' },
	vim: {
		url: 'https://www.vim.org/',
		source: '',
		desc: 'Highly configurable text editor built to enable efficient text editing',
	},
	figma: {
		url: 'https://www.figma.com/',
		source: '',
		desc: 'Collaborative interface design tool',
	},
	sketch: {
		url: 'https://www.sketch.com/',
		source: '',
		desc: 'Digital design toolkit for macOS',
	},
	npm: { url: 'https://www.npmjs.com/', source: '', desc: 'Package manager for JavaScript' },
	sourcehut: {
		url: 'https://sourcehut.org/',
		source: '',
		desc: 'Web-based software development platform',
	},
	substack: {
		url: 'https://substack.com/',
		source: '',
		desc: 'Platform for newsletters and subscription publishing',
	},
};
