import { IconGroups } from './types.ts';

export const iconGroups: IconGroups = [
	{
		group: 'Navigation & Arrows',
		header: '<small>*General Use*</small>',
		icons: [
			'up-caret',
			'down-caret',
			'left-caret',
			'right-caret',			
			'up-arrow',
			'down-arrow',			
			'left-arrow',
			'right-arrow',
			'bars',
			'forward-slash',
			'close',
		],
	},
	{
		group: 'Actions & Editing',
		header: '<small>*General Use*</small>',
		icons: [
			'pencil',
			'pen',
			'document',
			'add-document',
			'setting',
			'external',
			'download',
			'cloud-download',
			'rocket',
			'star',
			'puzzle',
			'list-format',
			'random',
			'comment',
			'comment-alt',
			'approve-check',
			'approve-check-circle',
			'translate',
			'heart',
		],
	},
	{
		group: 'Content, Status & System',
		header: '<small>*General Use*</small>',
		icons: [
			'moon',
			'sun',
			'laptop',
			'open-book',
			'information',
			'magnifier',
			'seti:image',
			'seti:video',
			'seti:audio',
			'seti:todo',
			'seti:plan',
			'seti:pipeline',
			'seti:happenings',
			'seti:lock',
			'seti:license',
			'seti:code-search',
			'email',
			'phone',
			'seti:folder',
			'seti:config',
			'seti:favicon',
			'seti:info',
			'seti:clock',
			'seti:notebook',
			'seti:db',
			'seti:default',
			'seti:shell',
			'seti:ignored',
			'error',
			'warning',
		],
	},
	{
		group: 'Programming & Scripting Languages',
		icons: [
			'seti:argdown',
			'seti:asm',
			'seti:c',
			'seti:c-sharp',
			'seti:clojure',
			'seti:coldfusion',
			'seti:cpp',
			'seti:crystal',
			'seti:crystal_embedded',
			'seti:d',
			'seti:dart',
			'seti:elixir',
			'seti:elm',
			'seti:f-sharp',
			'seti:go',
			'seti:graphql',
			'seti:hacklang',
			'seti:haskell',
			'seti:haxe',
			'seti:java',
			'seti:javascript',		
			'seti:julia',	
			'seti:kotlin',
			'seti:livescript',
			'seti:lua',
			'seti:nim',
			'seti:ocaml',
			'seti:pddl',
			'seti:perl',
			'seti:php',
			'seti:powershell',
			'seti:prolog',			
			'seti:purescript',
			'seti:python',
			'seti:R',
			'seti:rescript',
			'seti:ruby',
			'seti:rust',
			'seti:scala',
			'seti:swift',
			'seti:typescript',
			'seti:vala',
			'seti:zig',
		],
	},
	{
		group: 'Web & Markup',
		icons: [
			'seti:css',
			'seti:haml',
			'seti:html',
			'seti:jade',
			'seti:jinja',
			'seti:json',
			'seti:markdown',
			'mdx',
			'seti:mustache',
			'seti:nunjucks',
			'seti:pug',
			'seti:liquid',
			'seti:sass',
			'seti:slim',
			'seti:smarty',
			'seti:stylus',
			'seti:twig',			
			'seti:xml',
			'seti:yml',
		],
	},
	{
		group: 'Frameworks & Tools',
		icons: [
			'alpine',
			'astro',
			'backstage',
			'biome',
			'bun',
			'seti:cake',
			'seti:cake_php',
			'seti:cu',
			'deno',
			'seti:grails',
			'seti:ionic',
			'node',			
			'seti:odata',
			'pkl',
			'seti:platformio',
			'seti:react',
			'seti:spring',
			'starlight',
			'seti:svelte',
			'seti:vue',
		],
	},
	{
		group: 'Package Managers & Build Systems',
		icons: [
			'seti:babel',
			'seti:bazel',
			'seti:bower',			
			'seti:elixir_script',
			'seti:gradle',
			'seti:grunt',
			'seti:gulp',
			'seti:hex',
			'homebrew',
			'jsr',
			'seti:makefile',
			'seti:maven',
			'nix',
			'npm',
			'seti:npm',			
			'pnpm',			
			'seti:rollup',
			'seti:sbt',			
			'seti:vite',		
			'seti:webpack',
			'seti:yarn',			
		],
	},
	{
		group: 'Development Services',
		icons: [
			'azureDevOps',
			'seti:bicep',
			'bitbucket',						
			'cloudflare', // to put bsl on same row as mdo
			'seti:bsl', 
			'seti:mdo', // to put it with bsl
			'seti:code-climate',
			'codeberg',
			'codePen',			
			'seti:ethereum',
			'seti:firebase',			
			'stackOverflow',
			'hackerOne', // so github+gitlab are on a single line
			'github',
			'seti:github',
			'gitlab',
			'seti:gitlab',			
			'seti:heroku',						
			'netlify',
			'seti:prisma',
			'seti:salesforce',
			'sourcehut',
			'vercel',			
		],
	},
	{
		group: 'Development Tools',
		icons: [
			'confluence',
			'seti:docker',
			'seti:eslint',
			'seti:git',
			'seti:jenkins',
			'jetbrains',			
			'jira',
			'seti:karma',			
			'seti:puppet',
			'storybook',
			'seti:stylelint',
			'seti:sublime',
			'seti:terraform',			
			'vim',
			'vscode',
			'zed',
		],
	},
	{
		group: 'Word Processing, Design & Media',
		icons: [
			'figma',
			'seti:firefox',
			'seti:godot',
			'seti:illustrator',
			'seti:photoshop',
			'sketch',
			'seti:word',			
		],
	},
	{
		group: 'File types, Files & Protocols',
		icons: [			
			'seti:csv',
			'seti:font',
			'seti:pdf',
			'rss',
			'seti:svg',
			'seti:tex',
			'seti:tsconfig',
			'seti:wgt', // before wasm to let wasm and wat live side by side
			'seti:wasm',
			'seti:wat',			
			'seti:xls',
			'seti:zip',
		],
	},

	{
		group: 'Content Creators',
		icons: [
			'instagram',
			'openCollective',
			'patreon',
			'pinterest',
			'reddit',
			'substack',
			'tiktok',
			'twitch',
			'youtube',
		],
	},

	{
		group: 'Social Networks',
		icons: [
			'blueSky',
			'facebook',
			'farcaster',
			'linkedin',
			'mastodon',
			'nostr',			
			'twitter', 
			'x.com',
			'threads', // so twitter and x are beside each other
		],
	},
	{
		group: 'Communication',
		icons: [
			'discord',
			'discourse',
			'gitter',
			'matrix',
			'microsoftTeams',
			'signal',
			'slack',
			'telegram',
			'zulip',
		],
	},
	{
		group: 'OS & Platforms',
		icons: ['apple', 'linux', 'seti:windows'],
	},
];
